kalah:
  game:
    settings:
      num-of-pits: 6
      num-of-stones: 6

spring:
  data:
    mongodb:
      database: kalah
    rest:
      basePath: /api
  jackson:
    serialization:
      INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
